### PR TITLE
Added PKGBUILD 

### PR DESCRIPTION
**Pull request by giacomogallina**
It's the first time i write a PKGBUILD, so it's very likely that i made some mistakes, but it seems to work for me

### CODE REVIEW

**Comment by Hades0299** [comment]
As Programm is written as a bash-script, bash should be added to the depends

**Comment by Hades0299** [comment]
Well it is in the base metapackage, so most people will install it, bu better explicit to find those, that don't have it installed ;)

**Comment by Hades0299** [comment]
It might also be helpfull, to give the user the information, that he needs to add `alias go2='. go2'` to his .bashrc. Or add a file to `/etc/profile.d/` with the alias?

Something like this in `package()`:
```
mkdir -p "$pkgdir/etc/profile.d/
echo "alias go2='. go2'" > go2.sh
```

**Comment by ControlxFreak** [comment]
Awesome stuff! Thank you guys. I did not know how simple it was to make a PKGBUILD - it certainly intimidated me at first.

Maybe this is a dumb question but how does pkgbuild handle uninstallation?  Does it just rm -rf the $pkgdir?  If not, does this script need an uninstall function?

**Comment by Hades0299** [comment]
As far as i know, if you uninstall, all the files created while installation are removed, so configfiles are kept. I don't know whether that is done by `rm -rf $pkgdir`.

**Comment by ControlxFreak** [comment]
Cool - I was having a bit of trouble finding something online that talks about uninstallation process so I assume it is built in somehow.  I'm going to give it a few tests today and I'll merge tonight & push to the AUR if all is dandy.

**Comment by ControlxFreak** [comment]
I ran namcap for a sanity check and tested it using makepkg and I was able to install, use it and remove it using pacman.  Looks good!

**Pull request merged**
